export const GLOBAL_EVENTS = {
  CHANGE_STORE: 'CHANGE_STORE',
  CHANGE_LOCALE: 'CHANGE_LOCALE',
  CHANGE_THEME: 'CHANGE_THEME',
  CHANGE_THEME_DARK: 'CHANGE_THEME_DARK',
  CHANGE_THEME_LIGHT: 'CHANGE_THEME_LIGHT',
  CHANGE_THEME_SYSTEM: 'CHANGE_THEME_SYSTEM',
};

export const ORDER_EVENTS = {
  PREVIEW_IMAGE: 'PREVIEW_IMAGE',
};
